apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume
  namespace: three-tier
spec:
  storageClassName: ebs-csi-driver-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
