apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  namespace: three-tier
spec: 
  storageClassName: sc-aws
  accessModes:  
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
